packages:
  # all packages in direct subdirs of packages/
  - 'ragged'
  # all packages in subdirs of components/
  - 'workspace'
  # # exclude packages that are inside test directories
  # - '!**/test/**'
